# Generated by Django 3.0.5 on 2020-09-09 15:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogg',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='like_blogg', to=settings.AUTH_USER_MODEL),
        ),
    ]
